name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.4
    
    - name: Install dependencies
      run: |
        haxelib install flixel
        haxelib install lime
        haxelib install openfl
    
    - name: Build for HTML5
      run: haxe -main Main -cp source -lib flixel -js bin/html5/ClickerGame.js --macro "flixel.system.FlxBasePreloader.disable()"
    
    - name: Build for Android
      run: |
        haxelib run lime setup android
        haxe -main Main -cp source -lib flixel -android -D android -D lime_native bin/android/ClickerGame.apk
    
    - name: Upload HTML5 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html5-build
        path: bin/html5/
    
    - name: Upload Android APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: bin/android/ClickerGame.apk
